spring:
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis

server:
  port: 8080

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show-sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          fetch_size: 500
          batch_versioned_data: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:security;MODE=MYSQL;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    url: jdbc:h2:mem:redis
    user: sa
    password:
    baseline-on-migrate: true